import FeatureBox from "./FeatureBox";

const feature = [
  {
    title: "AI Contract Generation",
    description:
      "Input prompts and details, and watch as LegalGenius dynamically generates comprehensive contracts and agreements, streamlining the drafting process and ensuring accuracy.",
    benefit:
      "Save hours of manual work, increase efficiency, and minimize errors in contract creation.",
    image: "/ai.png",
  },
  {
    title: "Document Understanding",
    description:
      "Easily upload legal documents to LegalGenius and receive clear, concise explanations generated by our AI algorithms. Understanding complex legal jargon has never been easier.",
    benefit:
      "Empower individuals to comprehend legal documents without the need for a lawyer, fostering accessibility and transparency in legal matters.",
    image: "/contract.png",
  },
  {
    title: "Case Comparison and Insights",
    description:
      "Upload current case documents to LegalGenius for instant comparison with past cases, providing valuable insights and references to inform legal strategies.",
    benefit:
      "Enhance case preparation, make informed decisions, and leverage past precedents to strengthen arguments.",
    image: "/case.png",
  },
];
const FeatureSection = () => {
  return (
    <div className="mx-5 md:mx-20">
      <div className="text-3xl font-bold text-center">Our Platform Feature</div>
      <div className="flex md:flex-row flex-col flex-wrap  ">
        {feature.map((e, index) => {
          return (
            <FeatureBox
              title={e.title}
              description={e.description}
              benefit={e.benefit}
              key={index}
              imageLink={e.image}
            />
          );
        })}
      </div>
    </div>
  );
};
export default FeatureSection;
